---
env:
  NODE_ENV=production
  PORT=2368


  


setup:
# ----------------------------------------------------------------------------------------------------------
  # global
  - command: sudo apt update
  # - apt: upgrade -y
  - hosts:
    become: yes
    tasks:
      - name: apt
        apt: install hi
# ----------------------------------------------------------------------------------------------------------
  # docker
  - apt: apt-transport-https ca-certificates curl software-properties-common #for docker
  - command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - command: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu noble stable"
  - command: sudo apt update
  - apt: docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - command: sudo usermod -aG docker ${USER}


#    sudo apt install apt-transport-https ca-certificates curl software-properties-common
#    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
#    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu noble stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
#    sudo apt update
#    sudo apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
#    sudo snap install docker         # version 28.1.1+1, or
#    sudo apt  install docker.io      # version 26.1.3-0ubuntu1~24.04.1
#    sudo service docker start
  # docker
  - command: wget "https://desktop.docker.com/linux/main/amd64/docker-desktop-amd64.deb"
  - command: dpkg -i docker-desktop-amd64.deb
  - apt: -f

# ----------------------------------------------------------------------------------------------------------
  # node
  - apt: gnupg
  - command: curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
  - apt: nodejs

# ----------------------------------------------------------------------------------------------------------
  # yarn
  - command: sudo npm cache clean --force #to make sure everything works fine
  - command: sudo npm install --global yarn

# ----------------------------------------------------------------------------------------------------------
  # ghost
  # - git: --recurse-submodules git@github.com:TryGhost/Ghost
  - git: https://github.com/TryGhost/Ghost.git

  # TODO: does this wait in Ghost dir?
  - command: cd Ghost && export SSH_AUTH_SOCK && git init && yarn install && yarn setup
# TODO: git init works on windows. Check that.
# change     "setup": "yarn && git submodule update --init && NODE_ENV=development node .github/scripts/setup.js",






#######################################################
# mysqladmin -P 3306 -h 127.0.0.1 -u root -proot password ''
# sudo sysctl -w fs.inotify.max_user_watches=524288
# npx playwright install #before yarn test:acceptance in apps/admin-x-settings/
# ghsot_testing
#######################################################



    # env: 
    #   NODE_ENV=production
    #   PORT=2368
#- git: https://github.com/.../ghost.git
  - command: sudo apt autoremove
  - command: sudo apt clean
  - command: sudo apt autoclean


jobs:
  build:
    - name: install
      command: npm install
    - name: build
      command: npm run build
    - name: test
      command: npm test
