---
env:
  NODE_ENV=production
  PORT=2368

setup:
# ----------------------------------------------------------------------------------------------------------
  # global
  - command: apt update
# ----------------------------------------------------------------------------------------------------------
  # docker
  - apt: apt-transport-https ca-certificates curl software-properties-common #for docker
  - command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - command: echo \
      "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  - command: apt update
  - apt: docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - command: usermod -aG docker ${USER}
  - command: systemctl start docker
  - command: systemctl enable docker
  - command: service docker start

# ----------------------------------------------------------------------------------------------------------
  # node
  - apt: gnupg
  - command: curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
  - apt: nodejs

# ----------------------------------------------------------------------------------------------------------
  # yarn
  - command: npm cache clean --force #to make sure everything works fine
  - command: npm install --global yarn

# ----------------------------------------------------------------------------------------------------------
  # ghost
  # - git: --recurse-submodules git@github.com:TryGhost/Ghost
  - git: https://github.com/TryGhost/Ghost.git

  # - command: cd Ghost && export SSH_AUTH_SOCK && git init && yarn install && yarn setup
# change     "setup": "yarn && git submodule update --init && NODE_ENV=development node .github/scripts/setup.js",

#######################################################
# mysqladmin -P 3306 -h 127.0.0.1 -u root -proot password ''
# sudo sysctl -w fs.inotify.max_user_watches=524288
# npx playwright install #before yarn test:acceptance in apps/admin-x-settings/
# ghsot_testing
#######################################################

  # clean workspace
  - command: apt autoremove
  - command: apt clean
  - command: apt autoclean


jobs:
  build:
    - name: Install global packages
      command: yarn global add nx husky ember-cli patch-package playwright
    - name: Install local packages
      command: cd Ghost && yarn add knex-migrator -W && yarn install
    - name: Install playwright chromium #for "yarn test:acceptance"
    # - name: Increase machine watchers
      # command: echo fs.inotify.max_user_watches= 131070 | tee -a /etc/sysctl.conf && sudo sysctl -p
    - name: Build Ghost
      command: cd Ghost && echo y | yarn setup
    - name: server test:unit
      env: NODE_ENV=testing
      command: cd Ghost && yarn test:unit
    - name: server test:acceptance
      command: cd Ghost/apps/admin-x-activitypub/ && yarn playwright install chromium && yarn test:acceptance
    - name: server lint
      command: cd Ghost && yarn lint
    - name: client test
      command: cd Ghost/ghost/admin/ && ember test && ember test --server